- name: Basic System Setup
  hosts: capsule-web
  become: true
  tasks:
    - name: Update all security-related package
      ansible.builtin.package:
        name: '*'
        state: 'latest'
        security: true

    - name: Create new user
      ansible.builtin.user:
        name: stefano
        state: present
        create_home: true
