- name: Basic System Setup
  hosts: ewb
  become: true
  tasks:
    - name: Update all security-related packages
      ansible.builtin.packages:
        name: '*'
        state: 'latest'
        security: true

    - name: Create new user
      ansible.builtin.packages:
        name: stefano
        state: present
        create_home: true