- name: Basic System Setup (logic test)
  hosts: capsule-web
  gather_facts: false
  tasks:
    - name: Ping host
      ansible.builtin.ping:

    - name: Show Host Name 
      ansible.builtin.debug:
        msg: "I'm running on host: {{ inventory_hostname }}"
